apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mailer-pub-sub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
scopes:
- node-app
- dotnet-app