apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mailer-pub-sub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  # type: pubsub.rabbitmq
  # version: v1
  # metadata:
  # - name: host
  #   value: "amqp://localhost:5672"
  # - name: durable
  #   value: "false"
  # - name: deletedWhenUnused
  #   value: "false"
  # - name: autoAck
  #   value: "false"
  # - name: reconnectWait
  #   value: "0"
  # - name: concurrency
  #   value: parallel
scopes:
- node-app
- dotnet-app